#!/bin/bash

##################################################################################################################
# Block IP addresses from failed login attempts. Default number of failed login attempts for script to add
# the IP to the iptables block list is 3. This can be changed with the number on the command line argument.
#
# Example: ./block_failed_logins 10
# This will only block IP addresses if there have been 10 or greater attempts.
#
##################################################################################################################
if [ $# -eq 0 ]
then
   num_bad_attempts=3
else
   num_bad_attempts=$1
fi
echo "number args is: $#"

# Get the list of bad IPs and put in a variable.
bads=$(lastb | awk '$3 ~ /[0-9]+\.[0-9]+\.[0-9]+\.[0-9]/{print $3}' | sort | uniq -c | sed -e 's/^[ ]*//' )
echo "$bads"


# For each bad IP add a DROP rule.
while read -r line
do
   #echo "line is: $line"
   counter=0
	for x in $line
	do
           if [ $counter -eq 0 ]
           then
              if [ $x -ge $num_bad_attempts ]
              then
                 echo "total is $x, which is more than $num_bad_attempts"
              fi
           fi
           ((counter+=1)) 
	done
done <<< "$bads"
