#!/bin/bash

# Get the list of bad IPs and put in a variable.
bads=$(lastb | awk '$0 ~ /[0-9]+\.[0-9]/{print $3}' | sort | uniq -c | sed -e 's/^[ ]*//' )
#echo "$bads"


# For each bad IP add a DROP rule.
while read -r line
do
   #echo "line is: $line"
   counter=0
	for x in $line
	do
           if [ $counter -eq 0 ]
           then
              if [ $x -gt 100 ]
              then
                 echo "total is $x, which is more than 100"
              fi
           fi
           ((counter+=1)) 
	done
done <<< "$bads"
